---
title: "Links"
author: "NRES 710"
date: "Fall 2022"
output: 
  html_document: 
    theme: yeti
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Please let me know if there are other links that you think should be included on this page!

[Weekly math/bio "Stats chats"](https://kevintshoemaker.github.io/StatsChats/)

# Methods links

## Download R:
 [CRAN website](https://cran.r-project.org/)  
 
## Download R Studio:   
 [Rstudio main site](https://www.rstudio.com/)     
 [R projects (useful feature of RStudio)](https://support.rstudio.com/hc/en-us/articles/200526207-Using-Projects)        
 [Rstudio online learning resources](https://www.rstudio.com/online-learning/)      
 
## R Introductory Tutorials and Courses
 [Datacamp's- "Intro to R"](https://www.datacamp.com/home)   
 [Prelude in R](https://preludeinr.com)      
 [R for beginners](https://cran.r-project.org/doc/contrib/Paradis-rdebuts_en.pdf)   
 [Hadley Wickhams "R for Data Science"](http://r4ds.had.co.nz/index.html)
 [Modern Dive](https://ismayc.github.io/moderndiver-book/)     
 [Data carpentry course](http://www.datacarpentry.org/semester-biology/)
 [Many other resources](https://cran.r-project.org/other-docs.html) 
 [Many R Books (and other useful resources)](http://rbasicsworkshop.weebly.com/books.html)    
 [NCEAS tutorial- oldie but goodie](https://www.nceas.ucsb.edu/files/scicomp/Dloads/RProgramming/BestFirstRTutorial.pdf)

## R Examples (some people learn best by just playing with existing code!)            
 [R by example](http://www.mayin.org/ajayshah/KB/R/)      

## R reference cards (print 'em out and hang by your office desk!)      
 [Short Reference Card](https://cran.r-project.org/doc/contrib/Short-refcard.pdf)  
 [More comprehensive reference card](https://cran.r-project.org/doc/contrib/Baggott-refcard-v2.pdf)    
 [Data management reference card](https://sites.ualberta.ca/~ahamann/teaching/renr690/R_Cheat_Data.pdf)      
 [RStudio cheatsheets- very useful!](https://www.rstudio.com/resources/cheatsheets/)     
     Includes cheatsheets for R markdown, shiny, data wrangling with "dplyr" and much more!     

## R Markdown (for publishing and communicating in R. This website was built in R Markdown!)          
 [Guide for Pandoc Markdown](http://rmarkdown.rstudio.com/authoring_pandoc_markdown.html)   
 [Website development for RMarkdown](http://rmarkdown.rstudio.com/rmarkdown_websites.html)   
 [YAML: YAML Ain't Markup Language!](http://yaml.org/)   
 [a nice simple Markdown syntax guide](https://confluence.atlassian.com/bitbucketserver/markdown-syntax-guide-776639995.html)  

## GIT (for sharing your code and collaborating with others!)        
 [Excellent intro GIT tutorial](https://try.github.io/)  

## Bayesian Statistics
 [Install JAGS](http://mcmc-jags.sourceforge.net/)         
 [MCMC for Dummies...](http://twiecki.github.io/blog/2015/11/10/mcmc-sampling/) (basis of MCMC lecture...)  
 [BUGS online manual](http://www.mrc-bsu.cam.ac.uk/wp-content/uploads/manual14.pdf)  
 [secret BUGS tricks](http://users.aims.ac.za/~mackay/BUGS/Manuals/Tricks.html)  
 [Approximate Bayesian Computation: overview](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1002803)   
 [Bayesian Methods for Hackers!](http://camdavidsonpilon.github.io/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/)    
 [NIMBLE (alternative implementation of BUGS language for R)](https://r-nimble.org/)  
 
## Generalized Linear Mixed Models
 [Solving convergence issues](https://rstudio-pubs-static.s3.amazonaws.com/33653_57fc7b8e5d484c909b615d8633c01d51.html)         

## Time Series Analysis
 [A regression approach to time series analysis](http://node101.psych.cornell.edu/Darlington/series/series0.htm)  
 
## Ordination
 [Practical guide to ordination for Ecologists](http://ordination.okstate.edu/index.html)  
 
## Tree-based machine learning
 [Breiman's guide to Random Forest](http://www.stat.berkeley.edu/~breiman/RandomForests/cc_home.htm)  
 [Vignette: boosted regression trees for species distribution modeling](https://cran.r-project.org/web/packages/dismo/vignettes/brt.pdf)  

## Structural Equation Modeling and Bayes Nets
 [Random but relevant blog post](http://blog.efpsa.org/2015/12/14/structural-equation-modeling-what-is-it-what-does-it-have-in-common-with-hippie-music-and-why-does-it-eat-cake-to-get-rid-of-measurement-error/)  
 ["bnlearn" package documentation for Bayes nets](http://www.bnlearn.com/)  
 
## Spatial Analysis in R
 ["raster" package vignette](https://cran.r-project.org/web/packages/raster/vignettes/Raster.pdf)   

## Spatial Capture Recapture (secr)   
 ['secr' Google Group](https://groups.google.com/forum/#!forum/secrgroup)    
 [BUGS code for secr](http://www.mikemeredith.net/blog/1309_SECR_in_JAGS_patchy_habitat.htm)
 
 
# Data links

## Publicly available datasets, potentially for final project...  
(many links courtesy Tom Langen) 

### GOVERNMENT AGENCY DATA PORTALS 

[National Map](https://nationalmap.gov/) (Geospatial data on the environment, economy, and people of the US).   

[US Department of Agriculture Census of Agricultural Data](http://www.agcensus.usda.gov/) (Authoritative data on all aspects of agriculture in the US.)      

[Center for Disease Control & Prevention Data & Statistics](http://www.cdc.gov/datastatistics/) (Comprehensive data on all aspects of disease epidemiology.) 

[CDC ArboNet Disease Maps](https://wwwn.cdc.gov/arbonet/maps/ADB_Diseases_Map/index.html) (US County-scale maps of incidence patterns of various vectored diseases)     

[USGS Water Data for the Nation](http://waterdata.usgs.gov/nwis) (Hydrological and water-quality data from across the US.)     

[EPA National Rivers and Streams Assessment](https://www.epa.gov/national-aquatic-resource-surveys/nrsa)(Downloadable data on a national survey of stream water quality)   

[EPA Environmental Dataset Gateway](https://edg.epa.gov/metadata/catalog/main/home.page) (EPA environmental data portal)   

[The Multi-resolution Land Characteristics Consortium (MRLC) National Land Cover Database](http://www.mrlc.gov/) (Land cover or land use, canopy cover, and impermeable surface area of the entire US, at a resolution of 30 m x 30 m, based on remote sensing data from satellite imagery.)  

[US Fish & Wildlife Service National Wetlands Inventory](http://www.fws.gov/wetlands/) (Wetlands greater than 1 acre are mapped and classified throughout the US, Puerto Rico and US territories. Data can be examined using the [Wetland Mapper](http://www.fws.gov/wetlands/Data/Mapper.html) and then downloaded for use by a GIS application, or can by inspected directly using [Google Earth](http://www.fws.gov/wetlands/Data/GoogleEarth.html))   

[USDA Forest Inventory and Analysis National Program](http://fia.fs.fed.us/)        

[Forest Inventory Data Online (FIDO)](http://fia.fs.fed.us/tools-data/default.asp) (Highly-detailed periodic surveys of forest composition at sites throughout the US.)      

[US Geological Survey](http://www.usgs.gov/) (Reports, data analysis, maps, and raw data on a diversity of topics related to environmental science, including biodiversity and emerging diseases.)

[NOAA National Climate Data Center](http://www.ncdc.noaa.gov/oa/ncdc.html) (Extensive data archives of climate data, including paleoclimate.)

[NASA Global Change Master Directory](http://gcmd.nasa.gov/index.html) (Data on all aspects of global change, includes data on climate, land use, biodiversity and human dimensions.)    

[Oak Ridge National Laboratory Distributed Active Archive Center for Biogeochemical Dynamics(ORNL DAAC)](https://daac.ornl.gov/get_data/) (A NASA-sponsored source for biogeochemical and ecological data and models useful in environmental research.)    

[Land Processes DAAC](https://lpdaac.usgs.gov/)    

[Global Hydrology DAAC](https://ghrc.nsstc.nasa.gov/home/)     

[Socioeconomic DAAC](http://sedac.ciesin.columbia.edu/)      



### ENVIRONMENTAL DATA CLEARINGHOUSES

[Pole to Pole Ecological Research Lattice of Sites (P2ERLS)](http://www.p2erls.net/) (Portal to research stations and research networks, including their data archives.)  

[Weatherspark](http://weatherspark.com/) (Visualized time-series data on local climate at sites around the globe.)  

[Long Term Ecological Research (LTER) Network](http://www.lternet.edu/) (Network of research stations that have standardized monitoring programs as well as site-specific research. Sites are mandated to make data publicly available on the web.)  

[PRISM Climate Data](http://www.prism.oregonstate.edu/) (one of the most widely-used sites for downloading interpolated climate records for the USA)     

[LANDFIRE Program](https://www.landfire.gov/) (Great US-based site for obtaining GIS layers relevant for fire modeling)     

[WorldClim](http://www.worldclim.org/) (global climate layers (gridded climate data) with a spatial resolution of about 1 km2)     

[DayMet](https://daymet.ornl.gov/dataaccess.html) (gridded estimates of daily weather parameters for North America)    


### BIODIVERSITY DATA CLEARINGHOUSES /ARCHIVES
[International Union for the Conservation of Nature (IUCN) Redlist](http://www.iucnredlist.org/) (Searchable list of the world’s threatened and endangered plants and animal species on the IUCN Redlist.)   

[National Biological Information Infrastructure](http://www.nbii.gov/) (Data archive and clearinghouse for biological data from the US. Also provides standards for metadata.)  

[Biological Inventories of the World’s Protected Areas](http://www.ice.ucdavis.edu/bioinventory/bioinventory.html) (databases containing documented, taxonomically harmonized species inventories of plants and animals reported from the world's protected areas.)      

[Global Biodiversity Information Facility](http://data.gbif.org/welcome.htm) (international network and research infrastructure funded by the world’s governments and aimed at providing anyone, anywhere, open access to data about all types of life on Earth.)     

[Global Population Dynamics Data Base](http://www3.imperial.ac.uk/cpb/research/patternsandprocesses/gpdd) (5000 population size time series for 1400 species, most of which have at least ten years of data. There are data on the natural history of the organism and the location & method of sampling.)  

[USGS Breeding Bird Survey](http://www.pwrc.usgs.gov/BBS/) (The BBS is a long-term, large-scale, international avian monitoring program initiated in 1966 to track the status and trends of North American bird populations.)     

[Bird Studies Canada Nature Counts](http://www.bsc-eoc.org/birdmon/default/main.jsp) (Bird survey data archive for Canada, includes point counts and many other types of surveys.)  

[Avian Knowledge Network](http://www.avianknowledge.net/content/datasets)  (Archive of aggregated bird surveys from many organizations and studies across throughout the western hemisphere, including Latin America.)  

[NatureServe](http://www.natureserve.org/getData/index.jsp)  (Data on species of plants and animals in the Western Hemisphere, including detailed range maps)   

[NEON: National Ecological Observatory Network](https://www.neonscience.org/)  (NEON collects and provides open data from 81 field sites across the United States that characterize and quantify how our nation's ecosystems are changing)      


### RESEARCH PROJECT DATA ARCHIVES
[Dryad](http://datadryad.org/) (Data archives for bioscience data from peer-reviewed journal articles from a large consortium of journals)   

[Ecological Society of America (ESA) Data Registry](https://data.esa.org/esa/style/skins/esa/index.jsp)
Archive of ecological and environmental data from ESA publications)  

[National Center for Ecological Assessment & Synthesis (NCEAS) Data Repository](http://knb.ecoinformatics.org/knb/style/skins/nceas/index.jsp) (Data archive of contributed data sets of all types of ecological data.)    

[EDI Data Portal](https://portal.edirepository.org/nis/home.jsp) (NSF-funded iniative to archive data from NSF DEB funded research projects)     





