---
title: "Study Guide, Midterm Exam"
author: "NRES 710"
date: "Fall 2022"
output: 
  html_document: 
    theme: yeti
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```


## Midterm exam

### Overview

The midterm exam will be a 'take home' style exam that is administered on Wed Oct 28. You will have our regular class period to work on the exam (9-10am). All exams will be due at 5pm. I don't expect you will need more than an hour to complete the exam. This is the only exam in this course- there is no final exam (just final projects!) 

The midterm exam is designed to test your understanding of basic concepts of classical statistics and programming and data operations in R. The exam will cover everything in the 'basic concepts' series of lectures. You are also expected to know how to perform basic operations with data in R and to have some basic facility with programming in R. All exam questions will be intended to gauge understanding of high-level concepts- for this exam you will NOT be expected to perform analyses in R (that is what the mini-lab sessions are for) or know the correct syntax for built-in functions in R (you can always just look up the correct syntax!). To study for this exam, I recommend reading through the 'basic concepts' lecture, reviewing the recorded lectures, and looking over the 'base R' modules from the R bootcamp (1.1:working with data objects, 1.2:managing data, 1.3:data visualization/statistics, and 1.4:programming)   

The exam will consist of short-answer questions. I will continue to update this as I write the exam so you know what to expect! 

This is meant to be an individual exam, so please complete the exam by yourself without consulting your classmates. In a normal year this exam would be closed book, although you would be allowed to bring one page of notes ('cheat sheet'). I don't want to subject you to an online-proctored exam. So... I can't stop you from consulting the web and with classmates, but please study as you would for a regular in-class closed-book exam, and if possible try to make a cheat sheet for yourself- the act of making the cheat sheet is a great way to study (at least it works well for me)!  


### Topics covered

NOTE: this is not necessarily an exhaustive list -- any topic covered in the 'basic concepts' website is fair game


#### Basic Statistics

* Inference about a population from a sample
* Classical null-hypothesis testing
* Frequentist probability (frequencies of outcomes under repeated sampling)
* Sampling distributions (sampling uncertainty)
* Central limit theorem (CLT)
* P-values: interpretation, correct usage and common mis-usage
* Type I and Type II errors, statistical power
* Replication and pseudoreplication
* The 'independence' assumption: what it is and why it's important 
* Summary statistics: sample mean, sample variance, sample standard deviation
* Standard error of the mean: computation and interpretation
* Degrees of freedom
* Confidence intervals: construction and interpretation
* Fisher's exact test
* Student's t test (for one sample) and the t-distribution
* z-test (test statistic follows a standard normal distribution)
* Chi-squared test
* One-tailed vs two-tailed tests (t-test and z-test)
* Normal distribution
* Probability mass function, probability density function, cumulative distribution function
* Quantiles
* Parametric vs. non-parametric statistics


#### Basic R

* For loops: basic syntax and application
* If-then-else: basic syntax and application. [vectorized alternative: the 'ifelse()' function]
* Custom functions: basic syntax for making your own custom function 
* Using existing functions in base R: sum, mean, sd, rnorm, dt, etc. [note: you don't have to memorize details like the names of the arguments or even the names of the functions themselves! All you need to know is how to call and use these functions! For example, I may ask you to write out an R command that computes the 99% quantile of a standard normal distribution, given the correct function name is either 'pnorm', 'dnorm', or 'qnorm']     
* Subsetting data objects (vectors, matrices, data frames) using square brackets, dollar signs, etc.  
* Basic use of Boolean operators (less than, equal to, greater than)
* Subsetting data objects using Boolean operators (e.g., 'my.data[which(my.data$col1<10),])

NOTE: I will not test you on data visualization in R. 
 















